orbs:
  node: circleci/node@4.1.0

version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - run: git clone "https://github.com/jamriou/backend.git"
      - run: git clone "https://github.com/jamriou/frontend.git"
      - run: cd frontend && npm install && npm run build
      - run: cp -r ./frontend/build ./backend
      - run: cd backend && ls
workflows:
  build:
    jobs:
      - checkoutAndTest
